PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRPD_EDEV_T_DTYP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRPD_EDEV_T_DTYP-DOC_TYPE .
    FIELD ZRPD_EDEV_T_DTYP-DESCRIPTION .
    FIELD ZRPD_EDEV_T_DTYP-DESCRIPTION_EN .
    FIELD ZRPD_EDEV_T_DTYP-VERIFY_METHOD .
    FIELD ZRPD_EDEV_T_DTYP-PARSER_CLASS .
    FIELD ZRPD_EDEV_T_DTYP-ACTIVE .
    FIELD ZRPD_EDEV_T_DTYP-DJTL_ATIP .
    FIELD ZRPD_EDEV_T_DTYP-INFOTYPE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRPD_EDEV_T_DTYP-DOC_TYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
