PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRPD_EDEV_T_DMAP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRPD_EDEV_T_DMAP-DOC_TYPE .
    FIELD ZRPD_EDEV_T_DMAP-FIELD_NAME .
    FIELD ZRPD_EDEV_T_DMAP-INFOTYPE .
    FIELD ZRPD_EDEV_T_DMAP-SUBTYPE .
    FIELD ZRPD_EDEV_T_DMAP-INFOTYPE_FIELD .
    FIELD ZRPD_EDEV_T_DMAP-CONVERSION_RULE .
    FIELD ZRPD_EDEV_T_DMAP-DEFAULT_VALUE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRPD_EDEV_T_DMAP-DOC_TYPE .
    FIELD ZRPD_EDEV_T_DMAP-FIELD_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
